# Generated by Django 4.2.7 on 2024-09-11 13:49

from django.db import migrations, models
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='post', max_length=64)),
                ('image', models.ImageField(upload_to='images/posts/')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('number_of_likes', models.IntegerField(default=0, editable=False)),
                ('number_of_comments', models.IntegerField(default=0, editable=False)),
                ('state', django_fsm.FSMField(choices=[('on_validation', 'On validation'), ('published', 'Published'), ('on_deletion', 'On deletion')], default='on_validation', max_length=50)),
                ('task_id', models.CharField(editable=False, null=True)),
            ],
        ),
    ]
