# Generated by Django 4.2.7 on 2023-11-15 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uid',
            new_name='id',
        ),
    ]
