# Generated by Django 4.2.7 on 2023-11-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_uid_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='uid',
        ),
    ]
