# Generated by Django 4.2.7 on 2024-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_previous',
            field=models.ImageField(default='0', upload_to='images/posts/prev/'),
            preserve_default=False,
        ),
    ]
