# Generated by Django 4.2.7 on 2026-05-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_image_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_previous',
            field=models.ImageField(editable=False, upload_to='images/posts/prev/'),
        ),
    ]
