# Generated by Django 4.2.7 on 2023-11-25 19:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_post_created_at_post_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
