# Generated by Django 4.2.7 on 2023-11-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(verbose_name='Last modified at'),
        ),
    ]
