# Generated by Django 4.2.7 on 2023-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_alter_post_created_at_alter_post_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
    ]
