# Generated by Django 4.2.7 on 2023-12-08 11:13

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_name_post_title_remove_post_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=django_fsm.FSMField(default='on_validation', max_length=50),
        ),
    ]
