# Generated by Django 4.2.7 on 2024-02-15 12:11

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_post_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='Empty description.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=django_fsm.FSMField(choices=[('on_validation', 'On validation'), ('published', 'Published'), ('on_deletion', 'On deletion')], default='on_validation', max_length=50),
        ),
    ]
