# Generated by Django 4.2.7 on 2024-02-16 21:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_post_number_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False),
        ),
    ]
