# Generated by Django 4.2.7 on 2024-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='task_id',
            field=models.CharField(null=True),
        ),
    ]
