# Generated by Django 4.2.7 on 2024-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_post_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_comments',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='task_id',
            field=models.CharField(editable=False, null=True),
        ),
    ]
