# Generated by Django 4.2.7 on 2023-11-15 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_remove_user_id_remove_user_uuid_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
