# Generated by Django 4.2.7 on 2024-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customer_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='cockandballtorture', max_length=256),
            preserve_default=False,
        ),
    ]
